# Generated by Django 3.2.25 on 2024-07-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[('it', 'it'), ('se', 'se'), ('ml', 'ml')], max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
